[build-system]
requires = ["uv_build>=0.12.19,<0.13"]
build-backend = "uv_build"

[project]
name = "zonneplan-telegram"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pydantic>=2.13.5",
    "requests>=2.34.2",
]

[dependency-groups]
dev = [
    "ruff>=0.16.9",
    "ty>=0.0.84",
]

[project.scripts]
zonneplan_telegram = "zonneplan_telegram.bot:main"

[tool.ruff]
line-length = 88

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "CPY", # Copyright rules
    "COM812", # Comma rule conflicting with `ruff format`
    "D", # Docstring rules
]

[tool.tox.env.lint]
description = "Run linters"
skip_install = true
deps = ["ruff"]
commands = [["ruff", "check"]]

[tool.tox.env.format]
description = "Run formatter"
skip_install = true
deps = ["ruff"]
commands = [["ruff", "format", "--check"]]

[tool.tox.env.type]
description = "Run type checker"
skip_install = true
deps = ["ty"]
commands = [["ty", "check"]]
