---
name: Send Telegram message

on:
  workflow_dispatch:

jobs:
  run-bot:
    name: ✈️
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.14"
      - uses: astral-sh/setup-uv@v5
      - run: uv run zonneplan_telegram
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          UV_FROZEN: 1
          UV_NO_DEV: 1
      - name: Create Pull Request for Data Updates
        uses: peter-evans/create-pull-request@v8.1.1
        id: pr
        with:
          commit-message: "chore(data): update price history"
          title: "chore(data): Auto-update Zonneplan price history"
          body: "Automatic update of prices history."
          branch: automated-data-update
          delete-branch: true
      - name: Approve pull request
        run: gh pr review ${{ steps.pr.outputs.pull-request-number }} --approve --body "${{ env.COMMENT }}"
        env:
          GH_TOKEN: ${{ secrets.PAT }}
          COMMENT: "✨ _This pull request has been automatically approved._"
      - name: Force merge
        run: gh pr merge ${{ steps.pr.outputs.pull-request-number }} --squash --admin
        env:
          GH_TOKEN: ${{ secrets.PAT }}
