---
name: 🐍

on:
  pull_request:

jobs:
  qualification:
    name: Qualification
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v7
        with:
          python-version: "3.14"
      - uses: astral-sh/setup-uv@v10.2.0
      - run: uv tool install tox --with tox-uv
      - run: tox
